# Generated by Django 3.0.8 on 2020-09-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='todo',
            new_name='post',
        ),
    ]
