# Generated by Django 3.0.8 on 2020-09-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200916_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='post',
            new_name='todo',
        ),
    ]
